### ISSUE TITLE
Server side loading crash

### ISSUE THREAD

**Issue by chainingsolid** [OpenMods/OpenPeripheral#232]
crash report
https://drive.google.com/file/d/0B-_co1rU7BAhNlh6SFVvbFNRSWs/view?usp=sharing

loads fine on my client
crashes during server loading

**Comment by boq** [comment]
ComputerCraft problem: `s_modemIcons` is stripped, but class constructor ` = new IIcon[4];` isn't. 

Should fail without OP after placing cable on server. Please verify and close if it does.

**Comment by chainingsolid** [comment]
none of the mods make it to the init stage, the crash is during the server loading mods

**Comment by boq** [comment]
> " without OP"

I'm fairly certain it's pure CC, and OP is just triggering in earlier, but without it, it WILL crash anyway, just on first cable use.

**Comment by chainingsolid** [comment]
there shouldn't be any cc blocks in the world I just installed cc and open peripheral at the same time  and the server crashes before its done loading, no mod receives a FMLIntilizationEvent the crash is during preInint and server only,  I haven't been able to even log on to the server to place a cable

**Comment by boq** [comment]
Read what I said once again.

If you have OP, it will crash on load, because CC derped. But if you remove OP, it will still crash due to same CC bug, but after you place cable. 

I just tested server with just CC and can confirm that only their issue, so I can just close this.
```
java.lang.NoSuchFieldError: s_modemIcons
	at dan200.computercraft.shared.peripheral.modem.TileCable.<clinit>(TileCable.java:43) ~[TileCable.class:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_31]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_31]
	at net.minecraft.tileentity.TileEntity.func_145827_c(TileEntity.java:104) ~[aor.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:496) ~[aqk.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41) ~[ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) ~[ChunkIOProvider.class:?]
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) ~[AsynchronousExecutor.class:?]
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) ~[AsynchronousExecutor.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) ~[ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:265) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:235) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:258) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```
